In [1]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import logging,sys

In [7]:
df=pd.read_csv("C:\\Users\\91903\\Desktop\\ML\\breast Cancer\\dataset.csv",header=1)
dataset = shuffle(np.array(df))

In [8]:
df.head()

,842302,M,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,...,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
1,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
2,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
3,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
4,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.1578,0.08089,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440

In [9]:
df.drop(df.columns[[0]], axis=1, inplace=True)
dataset = shuffle(np.array(df))

In [10]:
df.head()

,M,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,...,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
0,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
1,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
2,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
3,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
4,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.1578,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440

In [11]:
extracted_dataset= []
target = []

#extract target column
for row in dataset:
    extracted_dataset.append(row[1:])
    target.append(row[0])

In [12]:
target

['M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'M',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'M',
 'M',
 'B',
 'M',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'M',
 'B',
 'B',
 'M',
 'B',
 'M',
 'M',
 'M',
 'M',
 'M',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'M',
 'B',
 'B']

In [13]:
X_train, X_test, Y_train, Y_test= train_test_split(extracted_dataset,target,test_size=0.3)

In [14]:
model = MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
model.fit(X_train,Y_train)

C:\Users\91903\anaconda3\envs\Titanic1\lib\site-packages\sklearn\utils\validation.py:976: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  estimator=estimator,

MultinomialNB()

In [18]:
predicted = model.predict(X_test)
predicted

C:\Users\91903\anaconda3\envs\Titanic1\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)

array(['M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'M',
       'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B'], dtype='<U1')

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,predicted,normalize=True)

0.935672514619883

In [21]:
ll=[12.46,24.04,83.97,475.9,0.1186,0.2396,0.2273,0.08543,0.203,0.08243,0.2976,1.599,2.039,23.94,0.007149,0.07217,0.07743,0.01432,0.01789,0.01008,15.09,40.68,97.65,711.4,0.1853,1.058,1.105,0.221,0.4366,0.2075
]
print(type(X_test))
predicted = model.predict([ll])
predicted

<class 'list'>

array(['B'], dtype='<U1')